### ISSUE TITLE
Help to port Sia GPU Miner to CPU with AVX2

### ISSUE THREAD

**Issue by ghost** [sneves/blake2-avx2#2]
Here is repo. I tried to use this library, but I understand that code very-very hard. 
https://github.com/NebulousLabs/Sia-GPU-Miner

**Comment by sneves** [comment]
If I understand that code correctly, what you want is to be running 4 instances of BLAKE2b concurrently. So adapting the code in `blake2bp.c` would be your best bet, in particular all you need is to use the `BLAKE2B_COMPRESS_V4` macro. You are on your own, however, to adapt this for mining.

**Comment by tromp** [comment]
dear Samuel,

I'm a contestant in the Zcash Open Miner Contest and also trying to use your code to compute 4 independent (acutally just differing in the last few bytes of input) blake2b's simultaneously. While I'm making good progress, I have a question about licensing. Right now my https://github.com/tromp/equihash repo is using the MIT license, as encouraged by the contest rules. Do you know if this is compatible with the Creative Commons License that you have, and are you ok with my use of your code? I will of course provide full attribution!

kind regards,
-John

**Comment by sneves** [comment]
I don't really know for sure how these licenses interact. According to [this](https://softwareengineering.stackexchange.com/questions/250259/does-cc0-allow-sublicensing-of-derived-works), CC0 should be compatible with everything. CC0 is supposed to be as close to public domain as possible, so in principle I don't see why they would be incompatible.

**Comment by tromp** [comment]
dear Samuel,

> I don't really know for sure how these licenses interact. According to this, CC0 should be compatible with everything. CC0 is supposed to be as close to public domain as possible, so in principle I don't see why they would be incompatible.

Great, then I'll use your code under the MIT License.
Thanks so much for making that available!

regards,
-John
